analyze_vacancy:
  description: >
    Изучить текст резюме: "{resume}".
    Затем изучить текст вакансии: "{vacancy}".
    На основе этого сформировать отчет, включающий в себя список совпадений в требованиях к вакансии и компетенциях сотрудника.
  expected_output: >
    В ответе указать список совпадений с кратким комментарием в 1-3 предложениях.
  agent: analyst
  output_file: output/report.md

write_letter:
  description: >
    На основании отчета сформировать убедительное сопроводительное письмо.
    Допускается использование только той информации, которая указана в отчете.
  expected_output: >
    Написать убедительное сопроводительное письмо,
    которое подчеркивает преимущества соискателя и выгодно выделяет его среди других кандидатов.
    Сопроводительное письмо не должно быть длиннее двух абзацев.
  agent: applicant
  context:
    - analyze_vacancy
  output_file: output/letter.md
